# Generated by Django 5.1.5 on 2025-01-21 09:29

import multimedia_manager.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_files/', validators=[multimedia_manager.utils.validate_image_file])),
                ('title', models.CharField(blank=True, help_text='Título o descripción de la imagen.', max_length=255, null=True, verbose_name='Título')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
