# Generated by Django 5.1.5 on 2025-01-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades_autonomas', '0001_initial'),
        ('multimedia_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidadautonoma',
            name='imagen',
            field=models.ForeignKey(blank=True, help_text='Imagen de la Comunidad Autónoma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='multimedia_manager.mediafile', verbose_name='Imagen'),
        ),
    ]
